# Generated by Django 5.2.5 on 2026-01-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_name', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('badge_class', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('title', models.CharField(default='Yeni randevu', max_length=200)),
                ('client_full_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('attendees', models.PositiveIntegerField(default=1)),
                ('duration', models.PositiveIntegerField(default=15)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='home.instructor')),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
    ]
