# Generated by Django 5.1.15 on 2026-01-04 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_globalsettings_alter_instructor_badge_class_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='appointment_duration',
            field=models.PositiveIntegerField(default=15),
        ),
    ]
