# Generated by Django 5.1.15 on 2026-01-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_globalsettings_appointment_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date', 'instructor'], name='home_appoin_date_edf00c_idx'),
        ),
    ]
